// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "auth/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// EmailService is an autogenerated mock type for the EmailService type
type EmailService struct {
	mock.Mock
}

// SendSupportEmailToUser provides a mock function with given fields: userID, emailContent
func (_m *EmailService) SendSupportEmailToUser(userID uuid.UUID, emailContent domain.EmailContent) error {
	ret := _m.Called(userID, emailContent)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, domain.EmailContent) error); ok {
		r0 = rf(userID, emailContent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewEmailService interface {
	mock.TestingT
	Cleanup(func())
}

// NewEmailService creates a new instance of EmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEmailService(t mockConstructorTestingTNewEmailService) *EmailService {
	mock := &EmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
